# Uncomment the next line to define a global platform for your project
platform :ios, '13.5'

target 'testApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for testApp
  pod 'SnapKit'
  pod 'Then'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'Moya/RxSwift'
  pod 'SDWebImage'
end
